// "use client"
import { ContextProvider } from "@/context/ContextProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import { Component } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
 
      <Head>
        <title>Solana Scaffold Lite</title>
      </Head>

      <ContextProvider>
        <div className="flex flex-col h-screen">
          {/* <Notifications /> */}
          {/* <AppBar /> */}
          {/* <ContentContainer> */}
            {/* <Component {...pageProps} /> */}
            {/* <Footer /> */}
          {/* </ContentContainer> */}
          <body className={inter.className}>{children}</body> 
        </div>
      </ContextProvider>
    </html>
  );
}
